/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  _type: "image";
  _key: string;
}>;

export type LessonResource = {
  _type: "lessonResource";
  type: "article" | "documentation" | "code" | "download" | "video";
  title: string;
  description?: string;
  url: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon: "zap" | "layers" | "shield" | "rocket" | "code" | "database" | "gauge" | "git-branch";
  title: string;
  description: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type CourseModule = {
  _type: "courseModule";
  title: string;
  summary?: string;
  lessons: Array<{
    _key: string;
  } & LessonReference>;
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  videoUrl: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  durationSeconds: number;
  freePreview?: boolean;
  studentCount?: number;
  keyPoints?: Array<string>;
  notes?: BlockContent;
  proTip?: string;
  resources?: Array<{
    _key: string;
  } & LessonResource>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  level: "beginner" | "intermediate" | "advanced";
  price?: number;
  popular?: boolean;
  studentCount?: number;
  learningOutcomes?: Array<{
    _key: string;
  } & LearningOutcome>;
  instructor: InstructorReference;
  category: CategoryReference;
  modules: Array<{
    _key: string;
  } & CourseModule>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  expertise?: Array<string>;
  bio?: BlockContent;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SanityImageAssetReference | BlockContent | LessonResource | LearningOutcome | LessonReference | CourseModule | Lesson | SanityImageCrop | SanityImageHotspot | Slug | InstructorReference | CategoryReference | Course | Category | Instructor | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../web/sanity/lib/queries.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)]{"slug": slug.current}
export type COURSE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../web/sanity/lib/queries.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)]{"slug": slug.current}
export type LESSON_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../web/sanity/lib/queries.ts
// Variable: INSTRUCTOR_SLUGS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)]{"slug": slug.current}
export type INSTRUCTOR_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../web/sanity/lib/queries.ts
// Variable: COURSES_CATALOG_QUERY
// Query: *[_type == "course" && defined(slug.current)]    | order(popular desc, title asc){        _id,  title,  "slug": slug.current,  summary,  level,  price,  popular,  studentCount,  coverImage{  asset->{_id, url, metadata{lqip, dimensions}},  hotspot,  crop,  alt},  instructor->{    _id,    name,    "slug": slug.current,    photo{  asset->{_id, url, metadata{lqip, dimensions}},  hotspot,  crop,  alt}  },  category->{_id, title, "slug": slug.current},  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "durationSeconds": math::sum(modules[].lessons[]->durationSeconds)    }
export type COURSES_CATALOG_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  level: "advanced" | "beginner" | "intermediate";
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  } | null;
  instructor: {
    _id: string;
    name: string;
    slug: string;
    photo: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string;
    } | null;
  };
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  moduleCount: number;
  lessonCount: number;
  durationSeconds: number;
}>;

// Source: ../web/sanity/lib/queries.ts
// Variable: COURSES_BY_CATEGORY_QUERY
// Query: *[_type == "course" && defined(slug.current) && category->slug.current == $category]    | order(popular desc, title asc){        _id,  title,  "slug": slug.current,  summary,  level,  price,  popular,  studentCount,  coverImage{  asset->{_id, url, metadata{lqip, dimensions}},  hotspot,  crop,  alt},  instructor->{    _id,    name,    "slug": slug.current,    photo{  asset->{_id, url, metadata{lqip, dimensions}},  hotspot,  crop,  alt}  },  category->{_id, title, "slug": slug.current},  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "durationSeconds": math::sum(modules[].lessons[]->durationSeconds)    }
export type COURSES_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  level: "advanced" | "beginner" | "intermediate";
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  } | null;
  instructor: {
    _id: string;
    name: string;
    slug: string;
    photo: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string;
    } | null;
  };
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  moduleCount: number;
  lessonCount: number;
  durationSeconds: number;
}>;

// Source: ../web/sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(title asc){    _id,    title,    "slug": slug.current,    description,    "courseCount": count(*[_type == "course" && references(^._id)])  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  courseCount: number;
}>;

// Source: ../web/sanity/lib/queries.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  summary,  level,  price,  popular,  studentCount,  coverImage{  asset->{_id, url, metadata{lqip, dimensions}},  hotspot,  crop,  alt},  instructor->{    _id,    name,    "slug": slug.current,    photo{  asset->{_id, url, metadata{lqip, dimensions}},  hotspot,  crop,  alt}  },  category->{_id, title, "slug": slug.current},  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "durationSeconds": math::sum(modules[].lessons[]->durationSeconds),    learningOutcomes[]{_key, icon, title, description},    instructor->{      _id,      name,      "slug": slug.current,      expertise,      bio,      photo{  asset->{_id, url, metadata{lqip, dimensions}},  hotspot,  crop,  alt}    },    modules[]{      _key,      title,      summary,      "durationSeconds": math::sum(lessons[]->durationSeconds),      lessons[]->{        _id,        title,        "slug": slug.current,        durationSeconds,        freePreview,        poster{  asset->{_id, url, metadata{lqip, dimensions}},  hotspot,  crop,  alt}      }    }  }
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string;
  level: "advanced" | "beginner" | "intermediate";
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  } | null;
  instructor: {
    _id: string;
    name: string;
    slug: string;
    expertise: Array<string> | null;
    bio: BlockContent | null;
    photo: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string;
    } | null;
  };
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  moduleCount: number;
  lessonCount: number;
  durationSeconds: number;
  learningOutcomes: Array<{
    _key: string;
    icon: "code" | "database" | "gauge" | "git-branch" | "layers" | "rocket" | "shield" | "zap";
    title: string;
    description: string;
  }> | null;
  modules: Array<{
    _key: string;
    title: string;
    summary: string | null;
    durationSeconds: number;
    lessons: Array<{
      _id: string;
      title: string;
      slug: string;
      durationSeconds: number;
      freePreview: boolean | null;
      poster: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string;
      } | null;
    }>;
  }>;
} | null;

// Source: ../web/sanity/lib/queries.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    videoUrl,    durationSeconds,    freePreview,    studentCount,    keyPoints,    notes,    proTip,    poster{  asset->{_id, url, metadata{lqip, dimensions}},  hotspot,  crop,  alt},    resources[]{_key, type, title, description, url},    "course": *[_type == "course" && references(^._id)][0]{      _id,      title,      "slug": slug.current,      coverImage{  asset->{_id, url, metadata{lqip, dimensions}},  hotspot,  crop,  alt},      instructor->{_id, name, "slug": slug.current, photo{  asset->{_id, url, metadata{lqip, dimensions}},  hotspot,  crop,  alt}},      modules[]{        _key,        title,        "lessonIds": lessons[]._ref      }    }  }
export type LESSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  videoUrl: string;
  durationSeconds: number;
  freePreview: boolean | null;
  studentCount: number | null;
  keyPoints: Array<string> | null;
  notes: BlockContent | null;
  proTip: string | null;
  poster: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  } | null;
  resources: Array<{
    _key: string;
    type: "article" | "code" | "documentation" | "download" | "video";
    title: string;
    description: string | null;
    url: string;
  }> | null;
  course: {
    _id: string;
    title: string;
    slug: string;
    coverImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string;
    } | null;
    instructor: {
      _id: string;
      name: string;
      slug: string;
      photo: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string;
      } | null;
    };
    modules: Array<{
      _key: string;
      title: string;
      lessonIds: Array<string>;
    }>;
  } | null;
} | null;

// Source: ../web/sanity/lib/queries.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    expertise,    bio,    photo{  asset->{_id, url, metadata{lqip, dimensions}},  hotspot,  crop,  alt},    "courses": *[_type == "course" && references(^._id)]      | order(popular desc, title asc){          _id,  title,  "slug": slug.current,  summary,  level,  price,  popular,  studentCount,  coverImage{  asset->{_id, url, metadata{lqip, dimensions}},  hotspot,  crop,  alt},  instructor->{    _id,    name,    "slug": slug.current,    photo{  asset->{_id, url, metadata{lqip, dimensions}},  hotspot,  crop,  alt}  },  category->{_id, title, "slug": slug.current},  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "durationSeconds": math::sum(modules[].lessons[]->durationSeconds)      }  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  expertise: Array<string> | null;
  bio: BlockContent | null;
  photo: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  } | null;
  courses: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string;
    level: "advanced" | "beginner" | "intermediate";
    price: number | null;
    popular: boolean | null;
    studentCount: number | null;
    coverImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string;
    } | null;
    instructor: {
      _id: string;
      name: string;
      slug: string;
      photo: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string;
      } | null;
    };
    category: {
      _id: string;
      title: string;
      slug: string;
    };
    moduleCount: number;
    lessonCount: number;
    durationSeconds: number;
  }>;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"course\" && defined(slug.current)]{\"slug\": slug.current}\n": COURSE_SLUGS_QUERY_RESULT;
    "\n  *[_type == \"lesson\" && defined(slug.current)]{\"slug\": slug.current}\n": LESSON_SLUGS_QUERY_RESULT;
    "\n  *[_type == \"instructor\" && defined(slug.current)]{\"slug\": slug.current}\n": INSTRUCTOR_SLUGS_QUERY_RESULT;
    "\n  *[_type == \"course\" && defined(slug.current)]\n    | order(popular desc, title asc){\n      \n  _id,\n  title,\n  \"slug\": slug.current,\n  summary,\n  level,\n  price,\n  popular,\n  studentCount,\n  coverImage{\n  asset->{_id, url, metadata{lqip, dimensions}},\n  hotspot,\n  crop,\n  alt\n},\n  instructor->{\n    _id,\n    name,\n    \"slug\": slug.current,\n    photo{\n  asset->{_id, url, metadata{lqip, dimensions}},\n  hotspot,\n  crop,\n  alt\n}\n  },\n  category->{_id, title, \"slug\": slug.current},\n  \"moduleCount\": count(modules),\n  \"lessonCount\": count(modules[].lessons[]),\n  \"durationSeconds\": math::sum(modules[].lessons[]->durationSeconds)\n\n    }\n": COURSES_CATALOG_QUERY_RESULT;
    "\n  *[_type == \"course\" && defined(slug.current) && category->slug.current == $category]\n    | order(popular desc, title asc){\n      \n  _id,\n  title,\n  \"slug\": slug.current,\n  summary,\n  level,\n  price,\n  popular,\n  studentCount,\n  coverImage{\n  asset->{_id, url, metadata{lqip, dimensions}},\n  hotspot,\n  crop,\n  alt\n},\n  instructor->{\n    _id,\n    name,\n    \"slug\": slug.current,\n    photo{\n  asset->{_id, url, metadata{lqip, dimensions}},\n  hotspot,\n  crop,\n  alt\n}\n  },\n  category->{_id, title, \"slug\": slug.current},\n  \"moduleCount\": count(modules),\n  \"lessonCount\": count(modules[].lessons[]),\n  \"durationSeconds\": math::sum(modules[].lessons[]->durationSeconds)\n\n    }\n": COURSES_BY_CATEGORY_QUERY_RESULT;
    "\n  *[_type == \"category\" && defined(slug.current)] | order(title asc){\n    _id,\n    title,\n    \"slug\": slug.current,\n    description,\n    \"courseCount\": count(*[_type == \"course\" && references(^._id)])\n  }\n": CATEGORIES_QUERY_RESULT;
    "\n  *[_type == \"course\" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  \"slug\": slug.current,\n  summary,\n  level,\n  price,\n  popular,\n  studentCount,\n  coverImage{\n  asset->{_id, url, metadata{lqip, dimensions}},\n  hotspot,\n  crop,\n  alt\n},\n  instructor->{\n    _id,\n    name,\n    \"slug\": slug.current,\n    photo{\n  asset->{_id, url, metadata{lqip, dimensions}},\n  hotspot,\n  crop,\n  alt\n}\n  },\n  category->{_id, title, \"slug\": slug.current},\n  \"moduleCount\": count(modules),\n  \"lessonCount\": count(modules[].lessons[]),\n  \"durationSeconds\": math::sum(modules[].lessons[]->durationSeconds)\n,\n    learningOutcomes[]{_key, icon, title, description},\n    instructor->{\n      _id,\n      name,\n      \"slug\": slug.current,\n      expertise,\n      bio,\n      photo{\n  asset->{_id, url, metadata{lqip, dimensions}},\n  hotspot,\n  crop,\n  alt\n}\n    },\n    modules[]{\n      _key,\n      title,\n      summary,\n      \"durationSeconds\": math::sum(lessons[]->durationSeconds),\n      lessons[]->{\n        _id,\n        title,\n        \"slug\": slug.current,\n        durationSeconds,\n        freePreview,\n        poster{\n  asset->{_id, url, metadata{lqip, dimensions}},\n  hotspot,\n  crop,\n  alt\n}\n      }\n    }\n  }\n": COURSE_BY_SLUG_QUERY_RESULT;
    "\n  *[_type == \"lesson\" && slug.current == $slug][0]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    videoUrl,\n    durationSeconds,\n    freePreview,\n    studentCount,\n    keyPoints,\n    notes,\n    proTip,\n    poster{\n  asset->{_id, url, metadata{lqip, dimensions}},\n  hotspot,\n  crop,\n  alt\n},\n    resources[]{_key, type, title, description, url},\n    \"course\": *[_type == \"course\" && references(^._id)][0]{\n      _id,\n      title,\n      \"slug\": slug.current,\n      coverImage{\n  asset->{_id, url, metadata{lqip, dimensions}},\n  hotspot,\n  crop,\n  alt\n},\n      instructor->{_id, name, \"slug\": slug.current, photo{\n  asset->{_id, url, metadata{lqip, dimensions}},\n  hotspot,\n  crop,\n  alt\n}},\n      modules[]{\n        _key,\n        title,\n        \"lessonIds\": lessons[]._ref\n      }\n    }\n  }\n": LESSON_BY_SLUG_QUERY_RESULT;
    "\n  *[_type == \"instructor\" && slug.current == $slug][0]{\n    _id,\n    name,\n    \"slug\": slug.current,\n    expertise,\n    bio,\n    photo{\n  asset->{_id, url, metadata{lqip, dimensions}},\n  hotspot,\n  crop,\n  alt\n},\n    \"courses\": *[_type == \"course\" && references(^._id)]\n      | order(popular desc, title asc){\n        \n  _id,\n  title,\n  \"slug\": slug.current,\n  summary,\n  level,\n  price,\n  popular,\n  studentCount,\n  coverImage{\n  asset->{_id, url, metadata{lqip, dimensions}},\n  hotspot,\n  crop,\n  alt\n},\n  instructor->{\n    _id,\n    name,\n    \"slug\": slug.current,\n    photo{\n  asset->{_id, url, metadata{lqip, dimensions}},\n  hotspot,\n  crop,\n  alt\n}\n  },\n  category->{_id, title, \"slug\": slug.current},\n  \"moduleCount\": count(modules),\n  \"lessonCount\": count(modules[].lessons[]),\n  \"durationSeconds\": math::sum(modules[].lessons[]->durationSeconds)\n\n      }\n  }\n": INSTRUCTOR_BY_SLUG_QUERY_RESULT;
  }
}

